name = "panhub-shenzjd-com"
main = ".output/server/index.mjs"
compatibility_date = "2025-07-15"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".output/public"
binding = "ASSETS"

# D1 边缘数据库物理持久化绑定
[[d1_databases]]
binding = "DB"
database_name = "panhub-db"
database_id = "7299e484-6c0f-4719-94a1-bb59d8a9a0dd"

# 环境变量（与线上 Docker 保持一致）
[vars]
LOG_LEVEL = "info"